-- DUYS — MERGED, IDEMPOTENT SCHEMA
-- Generated by scripts/build-schema.mjs on 2026-09-08T08:06:23.244Z
-- Safe to run on a FRESH database OR an EXISTING one (converges).

-- ============================================================================
-- schema.sql
-- ============================================================================
-- DUYS PostgreSQL Database Schema
-- Unified schema replacing dual SQLite architecture

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================================================
-- Users & Authentication
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  google_id VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT DEFAULT '',
  username VARCHAR(255) UNIQUE NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  bio TEXT DEFAULT '',
  location VARCHAR(255) DEFAULT '',
  website VARCHAR(255) DEFAULT '',
  avatar_url TEXT DEFAULT '',
  banner_url TEXT DEFAULT '',
  
  -- Economy
  points INTEGER NOT NULL DEFAULT 0,
  duys_tokens NUMERIC(15, 2) NOT NULL DEFAULT 0,
  balance_cents INTEGER NOT NULL DEFAULT 0,
  
  -- Verification & Status
  verified_badge VARCHAR(50) DEFAULT '',
  verified_badge_expires TIMESTAMP,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  is_banned BOOLEAN NOT NULL DEFAULT false,
  
  -- Security
  twofa_secret TEXT DEFAULT '',
  twofa_enabled BOOLEAN NOT NULL DEFAULT false,
  
  -- Profile
  referred_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  wallet_address VARCHAR(255) DEFAULT '',
  ringtone_url TEXT DEFAULT '',
  theme VARCHAR(50) DEFAULT 'dark',
  last_seen TIMESTAMP,
  profile_slug VARCHAR(255) DEFAULT '',
  pinned_post_id INTEGER,
  
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_verified_badge CHECK (verified_badge IN ('', 'blue', 'gold', 'grey'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_verified_badge ON users(verified_badge);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at DESC);

-- ============================================================================
-- Social Graph
-- ============================================================================

CREATE TABLE IF NOT EXISTS follows (
  follower_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followee_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (follower_id, followee_id),
  CONSTRAINT no_self_follow CHECK (follower_id != followee_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_follower ON follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_followee ON follows(followee_id);

-- ============================================================================
-- Posts & Content
-- ============================================================================

CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(50) NOT NULL DEFAULT 'text',
  body TEXT DEFAULT '',
  title VARCHAR(500) DEFAULT '',
  channel_id INTEGER,
  repost_of INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  quote_of INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  
  -- Boost
  is_sponsored BOOLEAN NOT NULL DEFAULT false,
  boost_until TIMESTAMP,
  cta VARCHAR(255) DEFAULT '',
  landing_url TEXT DEFAULT '',
  
  -- Exclusive Content
  is_exclusive BOOLEAN NOT NULL DEFAULT false,
  unlock_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
  
  -- Scheduling
  scheduled_at TIMESTAMP,
  
  -- Engagement metrics
  like_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  repost_count INTEGER NOT NULL DEFAULT 0,
  quote_count INTEGER NOT NULL DEFAULT 0,
  view_count INTEGER NOT NULL DEFAULT 0,
  share_count INTEGER NOT NULL DEFAULT 0,
  
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP,
  
  CONSTRAINT valid_kind CHECK (kind IN ('text', 'image', 'video', 'poll', 'article'))
);

CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_channel ON posts(channel_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_scheduled ON posts(scheduled_at) WHERE scheduled_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_posts_deleted ON posts(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================================================
-- Media & Attachments
-- ============================================================================

CREATE TABLE IF NOT EXISTS media (
  id SERIAL PRIMARY KEY,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key VARCHAR(500) NOT NULL,
  url TEXT NOT NULL,
  mime VARCHAR(100) DEFAULT '',
  kind VARCHAR(50) DEFAULT 'image',
  width INTEGER,
  height INTEGER,
  duration INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_media_kind CHECK (kind IN ('image', 'video', 'audio'))
);

CREATE INDEX IF NOT EXISTS idx_media_post ON media(post_id);
CREATE INDEX IF NOT EXISTS idx_media_owner ON media(owner_id);

-- ============================================================================
-- Engagement
-- ============================================================================

CREATE TABLE IF NOT EXISTS likes (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_likes_post ON likes(post_id);
CREATE INDEX IF NOT EXISTS idx_likes_user ON likes(user_id);

CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  like_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author_id);

CREATE TABLE IF NOT EXISTS comment_likes (
  id SERIAL PRIMARY KEY,
  comment_id INTEGER NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(comment_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_comment_likes_comment ON comment_likes(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_user ON comment_likes(user_id);

CREATE TABLE IF NOT EXISTS post_unlocks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  paid NUMERIC(15, 2) NOT NULL DEFAULT 0,
  unlocked_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_unlocks_user ON post_unlocks(user_id);
CREATE INDEX IF NOT EXISTS idx_post_unlocks_post ON post_unlocks(post_id);

-- ============================================================================
-- Polls
-- ============================================================================

CREATE TABLE IF NOT EXISTS poll_options (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  label VARCHAR(500) NOT NULL,
  votes INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_poll_options_post ON poll_options(post_id);

CREATE TABLE IF NOT EXISTS poll_votes (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  option_id INTEGER NOT NULL REFERENCES poll_options(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_poll_votes_post ON poll_votes(post_id);
CREATE INDEX IF NOT EXISTS idx_poll_votes_user ON poll_votes(user_id);

-- ============================================================================
-- Link Previews & Hashtags
-- ============================================================================

CREATE TABLE IF NOT EXISTS link_previews (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  title VARCHAR(255) DEFAULT '',
  description TEXT DEFAULT '',
  image TEXT DEFAULT '',
  domain VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(post_id)
);

CREATE INDEX IF NOT EXISTS idx_link_previews_post ON link_previews(post_id);

CREATE TABLE IF NOT EXISTS hashtags (
  tag VARCHAR(255) PRIMARY KEY,
  post_count INTEGER NOT NULL DEFAULT 0,
  last_used TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS post_hashtags (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag VARCHAR(255) NOT NULL REFERENCES hashtags(tag) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(post_id, tag)
);

CREATE INDEX IF NOT EXISTS idx_post_hashtags_post ON post_hashtags(post_id);
CREATE INDEX IF NOT EXISTS idx_post_hashtags_tag ON post_hashtags(tag);

-- ============================================================================
-- Stories
-- ============================================================================

CREATE TABLE IF NOT EXISTS stories (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  media_key VARCHAR(500) DEFAULT '',
  media_url TEXT NOT NULL,
  media_kind VARCHAR(50) DEFAULT 'image',
  caption TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL DEFAULT (NOW() + INTERVAL '1 day'),
  
  CONSTRAINT valid_story_media_kind CHECK (media_kind IN ('image', 'video'))
);

CREATE INDEX IF NOT EXISTS idx_stories_author ON stories(author_id);
CREATE INDEX IF NOT EXISTS idx_stories_expires_at ON stories(expires_at);

CREATE TABLE IF NOT EXISTS story_views (
  id SERIAL PRIMARY KEY,
  story_id INTEGER NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(story_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_story_views_story ON story_views(story_id);
CREATE INDEX IF NOT EXISTS idx_story_views_user ON story_views(user_id);

CREATE TABLE IF NOT EXISTS story_reactions (
  id SERIAL PRIMARY KEY,
  story_id INTEGER NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(story_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_story_reactions_story ON story_reactions(story_id);
CREATE INDEX IF NOT EXISTS idx_story_reactions_user ON story_reactions(user_id);

-- ============================================================================
-- Live Streaming
-- ============================================================================

CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY,
  host_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(50) NOT NULL DEFAULT 'video',
  title VARCHAR(500) DEFAULT '',
  status VARCHAR(50) NOT NULL DEFAULT 'live',
  viewer_peak INTEGER NOT NULL DEFAULT 0,
  current_viewers INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMP,
  
  CONSTRAINT valid_room_kind CHECK (kind IN ('video', 'space')),
  CONSTRAINT valid_room_status CHECK (status IN ('live', 'ended'))
);

CREATE INDEX IF NOT EXISTS idx_rooms_host ON rooms(host_id);
CREATE INDEX IF NOT EXISTS idx_rooms_status ON rooms(status, created_at DESC);

CREATE TABLE IF NOT EXISTS room_messages (
  id SERIAL PRIMARY KEY,
  room_id INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_room_messages_room ON room_messages(room_id);
CREATE INDEX IF NOT EXISTS idx_room_messages_user ON room_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_room_messages_created_at ON room_messages(created_at DESC);

-- ============================================================================
-- Channels
-- ============================================================================

CREATE TABLE IF NOT EXISTS channels (
  id SERIAL PRIMARY KEY,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  handle VARCHAR(255) UNIQUE NOT NULL,
  description TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  banner_url TEXT DEFAULT '',
  invite_token VARCHAR(255) DEFAULT '',
  is_private BOOLEAN NOT NULL DEFAULT false,
  pinned_post_id INTEGER REFERENCES posts(id) ON DELETE SET NULL,
  subscriber_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_channels_owner ON channels(owner_id);
CREATE INDEX IF NOT EXISTS idx_channels_handle ON channels(handle);
CREATE INDEX IF NOT EXISTS idx_channels_invite_token ON channels(invite_token);

CREATE TABLE IF NOT EXISTS channel_subscriptions (
  id SERIAL PRIMARY KEY,
  channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(channel_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_channel_subscriptions_channel ON channel_subscriptions(channel_id);
CREATE INDEX IF NOT EXISTS idx_channel_subscriptions_user ON channel_subscriptions(user_id);

CREATE TABLE IF NOT EXISTS channel_members (
  id SERIAL PRIMARY KEY,
  channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL DEFAULT 'member',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(channel_id, user_id),
  CONSTRAINT valid_role CHECK (role IN ('owner', 'moderator', 'member'))
);

CREATE INDEX IF NOT EXISTS idx_channel_members_channel ON channel_members(channel_id);
CREATE INDEX IF NOT EXISTS idx_channel_members_user ON channel_members(user_id);

-- ============================================================================
-- Direct Messaging
-- ============================================================================

CREATE TABLE IF NOT EXISTS conversations (
  id SERIAL PRIMARY KEY,
  participant_1_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  participant_2_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT different_participants CHECK (participant_1_id != participant_2_id),
  CONSTRAINT ordered_participants CHECK (participant_1_id < participant_2_id),
  UNIQUE(participant_1_id, participant_2_id)
);

CREATE INDEX IF NOT EXISTS idx_conversations_p1 ON conversations(participant_1_id);
CREATE INDEX IF NOT EXISTS idx_conversations_p2 ON conversations(participant_2_id);
CREATE INDEX IF NOT EXISTS idx_conversations_updated ON conversations(updated_at DESC);

CREATE TABLE IF NOT EXISTS messages (
  id SERIAL PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  read_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_read ON messages(read_at) WHERE read_at IS NULL;

-- ============================================================================
-- Notifications
-- ============================================================================

CREATE TABLE IF NOT EXISTS notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  actor_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT DEFAULT '',
  entity_type VARCHAR(50),
  entity_id INTEGER,
  read_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_kind CHECK (kind IN ('like', 'comment', 'follow', 'mention', 
                                        'repost', 'quote', 'message', 'subscription', 
                                        'verification', 'payment', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(user_id, read_at) WHERE read_at IS NULL;

-- ============================================================================
-- Verification & Identity
-- ============================================================================

CREATE TABLE IF NOT EXISTS verifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  data JSONB DEFAULT '{}',
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMP,
  reason TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_kind CHECK (kind IN ('email', 'phone', 'id', 'face')),
  CONSTRAINT valid_status CHECK (status IN ('pending', 'approved', 'rejected', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_verifications_user ON verifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_verifications_status ON verifications(status);

-- ============================================================================
-- Wallet & Transactions
-- ============================================================================

CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(50) NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  balance_after NUMERIC(15, 2) NOT NULL,
  description TEXT DEFAULT '',
  reference_id VARCHAR(255),
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_kind CHECK (kind IN ('deposit', 'withdrawal', 'purchase', 'refund', 
                                        'unlock', 'subscription', 'referral', 'boost'))
);

CREATE INDEX IF NOT EXISTS idx_transactions_user ON transactions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_kind ON transactions(kind);
CREATE INDEX IF NOT EXISTS idx_transactions_reference ON transactions(reference_id);

CREATE TABLE IF NOT EXISTS wallet_addresses (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  address VARCHAR(255) NOT NULL,
  blockchain VARCHAR(50) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT false,
  primary_wallet BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, address)
);

CREATE INDEX IF NOT EXISTS idx_wallet_addresses_user ON wallet_addresses(user_id);

-- ============================================================================
-- Boosts & Promotions
-- ============================================================================

CREATE TABLE IF NOT EXISTS boosts (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  advertiser_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  budget NUMERIC(15, 2) NOT NULL,
  spent NUMERIC(15, 2) NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  cta VARCHAR(255) DEFAULT '',
  landing_url TEXT DEFAULT '',
  starts_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ends_at TIMESTAMP NOT NULL,
  impressions INTEGER NOT NULL DEFAULT 0,
  clicks INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_boost_status CHECK (status IN ('pending', 'active', 'paused', 'ended'))
);

CREATE INDEX IF NOT EXISTS idx_boosts_advertiser ON boosts(advertiser_id);
CREATE INDEX IF NOT EXISTS idx_boosts_status ON boosts(status);
CREATE INDEX IF NOT EXISTS idx_boosts_ends_at ON boosts(ends_at);

-- ============================================================================
-- Referrals
-- ============================================================================

CREATE TABLE IF NOT EXISTS referrals (
  id SERIAL PRIMARY KEY,
  referrer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  referred_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reward_given NUMERIC(15, 2) NOT NULL DEFAULT 0,
  reward_redeemed NUMERIC(15, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(referrer_id, referred_user_id)
);

CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referred ON referrals(referred_user_id);

-- ============================================================================
-- Reports & Moderation
-- ============================================================================

CREATE TABLE IF NOT EXISTS reports (
  id SERIAL PRIMARY KEY,
  reporter_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entity_type VARCHAR(50) NOT NULL,
  entity_id INTEGER NOT NULL,
  reason VARCHAR(255) NOT NULL,
  description TEXT DEFAULT '',
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action_taken VARCHAR(255),
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  CONSTRAINT valid_entity_type CHECK (entity_type IN ('user', 'post', 'comment', 'message')),
  CONSTRAINT valid_report_status CHECK (status IN ('pending', 'reviewing', 'dismissed', 'actioned'))
);

CREATE INDEX IF NOT EXISTS idx_reports_reporter ON reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_entity ON reports(entity_type, entity_id);

-- ============================================================================
-- Admin & Logging
-- ============================================================================

CREATE TABLE IF NOT EXISTS admin_logs (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(255) NOT NULL,
  entity_type VARCHAR(50),
  entity_id INTEGER,
  details JSONB DEFAULT '{}',
  ip_address INET,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_logs_admin ON admin_logs(admin_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_logs_action ON admin_logs(action);

CREATE TABLE IF NOT EXISTS feature_flags (
  key VARCHAR(255) PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT false,
  description TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Triggers for updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_updated_at ON users;


CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS posts_updated_at ON posts;


CREATE TRIGGER posts_updated_at BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS comments_updated_at ON comments;


CREATE TRIGGER comments_updated_at BEFORE UPDATE ON comments
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS channels_updated_at ON channels;


CREATE TRIGGER channels_updated_at BEFORE UPDATE ON channels
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS conversations_updated_at ON conversations;


CREATE TRIGGER conversations_updated_at BEFORE UPDATE ON conversations
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS messages_updated_at ON messages;


CREATE TRIGGER messages_updated_at BEFORE UPDATE ON messages
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS verifications_updated_at ON verifications;


CREATE TRIGGER verifications_updated_at BEFORE UPDATE ON verifications
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS boosts_updated_at ON boosts;


CREATE TRIGGER boosts_updated_at BEFORE UPDATE ON boosts
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS feature_flags_updated_at ON feature_flags;


CREATE TRIGGER feature_flags_updated_at BEFORE UPDATE ON feature_flags
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();


-- ============================================================================
-- schema-migration-auth-2fa.sql
-- ============================================================================
-- DUYS Schema Migration: 2FA, App Config, Referrals
-- Run this ONCE against your production database.

-- App config for announcement banner, Google OAuth toggle
CREATE TABLE IF NOT EXISTS app_config (
  key VARCHAR(255) PRIMARY KEY,
  value TEXT NOT NULL,
  description TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Default announcement (empty = no banner)
INSERT INTO app_config (key, value, description)
VALUES ('announcement_text', '', 'Text for the top announcement banner on auth pages')
ON CONFLICT (key) DO NOTHING;

INSERT INTO app_config (key, value, description)
VALUES ('announcement_enabled', 'false', 'Enable/disable the announcement banner')
ON CONFLICT (key) DO NOTHING;

INSERT INTO app_config (key, value, description)
VALUES ('google_enabled', 'true', 'Enable Google OAuth login')
ON CONFLICT (key) DO NOTHING;

-- Referral column already exists in schema.sql (referred_by INTEGER REFERENCES users(id))
-- Ensure index exists for referral lookups
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by);
CREATE INDEX IF NOT EXISTS idx_users_twofa_enabled ON users(twofa_enabled);

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS app_config_updated_at ON app_config;


CREATE TRIGGER app_config_updated_at BEFORE UPDATE ON app_config
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();


-- ============================================================================
-- schema-migration-posts-depth.sql
-- ============================================================================
-- DUYS Schema Migration: Posts Depth
-- Run this ONCE against your production database.
-- Adds pinning support + per-user deduped post views (poll/exclusive/schedule/link_previews tables already exist).

-- 1) Pinned posts (profile pinning — one active pin per author)
ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS pinned_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_posts_pinned ON posts(author_id, is_pinned)
  WHERE is_pinned = true;

-- 2) Deduped post views (one view per (post, user))
CREATE TABLE IF NOT EXISTS post_views (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_post_views_post ON post_views(post_id);
CREATE INDEX IF NOT EXISTS idx_post_views_user ON post_views(user_id);

-- 3) Hashtag fuzzy lookup support (used by the search overlay + linkify)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_hashtags_tag_trgm ON hashtags USING gin (tag gin_trgm_ops);


-- ============================================================================
-- schema-migration-social-depth.sql
-- ============================================================================
-- DUYS Schema Migration: Social Depth (Phase 3)
-- Run this ONCE against your production database.
-- Adds group conversations, message reactions, blocks, mutes, message pins,
-- channel verifications, and live-room speaker/heart tracking. All tables are
-- additive — safe to run alongside existing schema.sql.

-- ============================================================================
-- 1) Message reactions (1:1 direct messages)
-- ============================================================================
CREATE TABLE IF NOT EXISTS message_reactions (
  id SERIAL PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(message_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_message_reactions_message ON message_reactions(message_id);

-- ============================================================================
-- 2) Message pins (pinned messages in a 1:1 conversation)
-- ============================================================================
CREATE TABLE IF NOT EXISTS message_pins (
  message_id INTEGER PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
  pinned_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pinned_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- 3) Conversation blocks & mutes for 1:1 messaging
-- ============================================================================
CREATE TABLE IF NOT EXISTS conversation_blocks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, blocked_id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_blocks_user ON conversation_blocks(user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_blocks_blocked ON conversation_blocks(blocked_id);

CREATE TABLE IF NOT EXISTS conversation_mutes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, conversation_id)
);
-- ============================================================================
-- 4) Group conversations
-- ============================================================================
CREATE TABLE IF NOT EXISTS group_conversations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invite_token VARCHAR(64) UNIQUE DEFAULT '',
  is_verified BOOLEAN NOT NULL DEFAULT false,
  verified_badge VARCHAR(20) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_group_conversations_invite ON group_conversations(invite_token);
CREATE INDEX IF NOT EXISTS idx_group_conversations_created ON group_conversations(created_at DESC);

CREATE TABLE IF NOT EXISTS group_members (
  id SERIAL PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES group_conversations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL DEFAULT 'member',
  muted BOOLEAN NOT NULL DEFAULT false,
  joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(group_id, user_id),
  CONSTRAINT valid_group_member_role CHECK (role IN ('owner', 'admin', 'member'))
);

CREATE INDEX IF NOT EXISTS idx_group_members_group ON group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id);

CREATE TABLE IF NOT EXISTS group_messages (
  id SERIAL PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES group_conversations(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  reply_to INTEGER REFERENCES group_messages(id) ON DELETE SET NULL,
  read_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_messages_group ON group_messages(group_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_group_messages_sender ON group_messages(sender_id);

CREATE TABLE IF NOT EXISTS group_message_reactions (
  id SERIAL PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES group_messages(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(message_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_message_reactions_msg ON group_message_reactions(message_id);

-- ============================================================================
-- 5) Channel depth: mutes + verifications
-- ============================================================================
CREATE TABLE IF NOT EXISTS channel_mutes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, channel_id)
);

CREATE INDEX IF NOT EXISTS idx_channel_mutes_user ON channel_mutes(user_id);

CREATE TABLE IF NOT EXISTS channel_verifications (
  id SERIAL PRIMARY KEY,
  channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge VARCHAR(20) NOT NULL DEFAULT 'blue',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  decided_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reason TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(channel_id, user_id),
  CONSTRAINT valid_channel_verify_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_channel_verifications_channel ON channel_verifications(channel_id);
CREATE INDEX IF NOT EXISTS idx_channel_verifications_user ON channel_verifications(user_id);
CREATE INDEX IF NOT EXISTS idx_channel_verifications_status ON channel_verifications(status);

-- ============================================================================
-- 6) Group verification (self-apply + admin review)
-- ============================================================================
CREATE TABLE IF NOT EXISTS group_verifications (
  id SERIAL PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES group_conversations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge VARCHAR(20) NOT NULL DEFAULT 'blue',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  decided_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reason TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(group_id, user_id),
  CONSTRAINT valid_group_verify_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_group_verifications_group ON group_verifications(group_id);
CREATE INDEX IF NOT EXISTS idx_group_verifications_user ON group_verifications(user_id);
CREATE INDEX IF NOT EXISTS idx_group_verifications_status ON group_verifications(status);

-- ============================================================================
-- 7) Channel view tracking (parity with legacy /c/<handle>/view/<post_id>)
-- ============================================================================

-- ============================================================================
-- 8) Live Spaces: speakers + hearts
-- ============================================================================
CREATE TABLE IF NOT EXISTS room_speakers (
  id SERIAL PRIMARY KEY,
  room_id INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(room_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_room_speakers_room ON room_speakers(room_id);
CREATE INDEX IF NOT EXISTS idx_room_speakers_user ON room_speakers(user_id);

CREATE TABLE IF NOT EXISTS room_hearts (
  id SERIAL PRIMARY KEY,
  room_id INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(room_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_room_hearts_room ON room_hearts(room_id);

-- ============================================================================
-- 9) WebRTC calls (signaling queue — server is a relay, not a TURN/STUN server)
-- ============================================================================
CREATE TABLE IF NOT EXISTS calls (
  id VARCHAR(64) PRIMARY KEY,
  room_id INTEGER REFERENCES rooms(id) ON DELETE SET NULL,
  conversation_id INTEGER REFERENCES conversations(id) ON DELETE SET NULL,
  caller_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(20) NOT NULL DEFAULT 'voice',
  status VARCHAR(20) NOT NULL DEFAULT 'ringing',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMP,
  CONSTRAINT valid_call_kind CHECK (kind IN ('voice', 'video')),
  CONSTRAINT valid_call_status CHECK (status IN ('ringing', 'active', 'ended', 'declined'))
);

CREATE INDEX IF NOT EXISTS idx_calls_caller ON calls(caller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_calls_status ON calls(status, created_at);

CREATE TABLE IF NOT EXISTS call_signals (
  id SERIAL PRIMARY KEY,
  call_id VARCHAR(64) NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  from_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  to_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(20) NOT NULL,
  data TEXT NOT NULL,
  emitted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  delivered BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_call_signals_call ON call_signals(call_id);
CREATE INDEX IF NOT EXISTS idx_call_signals_to ON call_signals(to_user_id, delivered);


-- ============================================================================
-- schema-migration-economy.sql
-- ============================================================================
-- DUYS Schema Migration: Economy & Monetization
-- Run this ONCE against your production database.
-- Adds ledgers, ad-earnings, token claims, tips, shop listings/purchases
-- and vault swaps. Existing tables (users.points, boosts, referrals,
-- transactions, wallet_addresses) are reused.

-- 1) Points & token ledger (reason-tagged deltas)
CREATE TABLE IF NOT EXISTS point_ledger (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  delta NUMERIC(15, 4) NOT NULL,
  reason VARCHAR(100) NOT NULL,
  ref VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_point_ledger_user ON point_ledger(user_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_point_ledger_reason ON point_ledger(reason);

-- 2) Rewarded-ad tracking (HypeLab)
CREATE TABLE IF NOT EXISTS ad_views (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reward INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ad_views_user ON ad_views(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS hypelab_events (
  id SERIAL PRIMARY KEY,
  event_id VARCHAR(255) NOT NULL UNIQUE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reward INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 3) Points -> DUYS token claims
CREATE TABLE IF NOT EXISTS token_claims (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  points_used INTEGER NOT NULL,
  tokens NUMERIC(15, 6) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  tx_hash VARCHAR(255) DEFAULT '',
  error_msg TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_claim_status CHECK (status IN ('pending', 'confirmed', 'failed', 'voided'))
);

CREATE INDEX IF NOT EXISTS idx_token_claims_user ON token_claims(user_id, created_at DESC);

-- 4) Tips (points and/or DUYS)
CREATE TABLE IF NOT EXISTS tips (
  id SERIAL PRIMARY KEY,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON DELETE SET NULL,
  amount_points INTEGER NOT NULL DEFAULT 0,
  amount_duys NUMERIC(15, 6) NOT NULL DEFAULT 0,
  message VARCHAR(280) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT tips_nonzero CHECK (amount_points > 0 OR amount_duys > 0)
);

CREATE INDEX IF NOT EXISTS idx_tips_sender ON tips(sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tips_recipient ON tips(recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tips_post ON tips(post_id);
-- 5) Creator shop (verified users sell downloadable files for DUYS)
CREATE TABLE IF NOT EXISTS shop_listings (
  id SERIAL PRIMARY KEY,
  seller_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(128) NOT NULL,
  description TEXT DEFAULT '',
  file_key VARCHAR(500) NOT NULL,
  file_url TEXT NOT NULL,
  file_name VARCHAR(255) DEFAULT '',
  price_duys NUMERIC(15, 6) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shop_listings_seller ON shop_listings(seller_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_shop_listings_active ON shop_listings(active);

CREATE TABLE IF NOT EXISTS shop_purchases (
  id SERIAL PRIMARY KEY,
  buyer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  listing_id INTEGER NOT NULL REFERENCES shop_listings(id) ON DELETE CASCADE,
  paid NUMERIC(15, 6) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(buyer_id, listing_id)
);

CREATE INDEX IF NOT EXISTS idx_shop_purchases_buyer ON shop_purchases(buyer_id);
CREATE INDEX IF NOT EXISTS idx_shop_purchases_listing ON shop_purchases(listing_id);

-- 6) Vault swaps (Buy/Sell DUYS <-> USDT, deposit-based settlement)
CREATE TABLE IF NOT EXISTS swaps (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  side VARCHAR(20) NOT NULL,
  from_token VARCHAR(20) NOT NULL,
  to_token VARCHAR(20) NOT NULL,
  from_amount NUMERIC(18, 8) NOT NULL,
  to_amount NUMERIC(18, 8) NOT NULL,
  rate NUMERIC(18, 10) NOT NULL DEFAULT 0,
  spread NUMERIC(10, 4) NOT NULL DEFAULT 0,
  user_address VARCHAR(255) DEFAULT '',
  deposit_token VARCHAR(20) NOT NULL DEFAULT '',
  status VARCHAR(50) NOT NULL DEFAULT 'awaiting_deposit',
  deposit_tx VARCHAR(255) DEFAULT '',
  payout_tx VARCHAR(255) DEFAULT '',
  error_msg TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_swap_side CHECK (side IN ('buy', 'sell', 'transfer')),
  CONSTRAINT valid_swap_status CHECK (status IN
    ('awaiting_deposit', 'deposit_seen', 'settling', 'completed', 'expired', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_swaps_user ON swaps(user_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_swaps_status ON swaps(status);

-- 7) Economy settings (admin-tunable via app_config)
INSERT INTO app_config (key, value, description) VALUES
  ('points_ad_reward', '10', 'Points awarded per rewarded ad view'),
  ('daily_ad_cap', '50', 'Max rewarded ad completions per user per day'),
  ('claim_points_per_token', '10', 'Points required for 1 DUYS claim'),
  ('claim_min_points', '100', 'Minimum points to start a claim'),
  ('claim_max_daily', '1', 'Max claims per day (regular users)'),
  ('claim_max_daily_verified', '3', 'Max claims per day (verified users)'),
  ('points_referral_bonus', '100', 'Points credited when a referred user signs up'),
  ('referral_earn_percent', '0.01', 'Referrer earns this share of referred users earnings'),
  ('fee_usd_boost_per_day', '1.00', 'USD price per boost-day'),
  ('swap_buy_enabled', 'true', 'Enable DUYS buy swaps'),
  ('swap_sell_enabled', 'true', 'Enable DUYS sell swaps'),
  ('token_price_override_enabled', 'false', 'Use the fixed token price below'),
  ('token_price_override_rate', '0', 'Fixed DUYS-per-USDT rate when override is on')
ON CONFLICT (key) DO NOTHING;

-- 8) Trigger for swaps.updated_at
DROP TRIGGER IF EXISTS swaps_updated_at ON swaps;
DROP TRIGGER IF EXISTS swaps_updated_at ON swaps;
CREATE TRIGGER swaps_updated_at BEFORE UPDATE ON swaps
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();


-- ============================================================================
-- schema-settings-migration.sql
-- ============================================================================
-- DUYS Schema Migration: Settings, Privacy, Blocked Users
-- Run this ONCE against your production database (in addition to schema.sql).

-- Privacy columns for users
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS who_can_message VARCHAR(20) NOT NULL DEFAULT 'everyone';
ALTER TABLE users ADD COLUMN IF NOT EXISTS show_online_status BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS push_notifications JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Blocked users
CREATE TABLE IF NOT EXISTS blocked_users (
  blocker_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (blocker_id, blocked_id),
  CONSTRAINT no_self_block CHECK (blocker_id != blocked_id)
);

CREATE INDEX IF NOT EXISTS idx_blocked_users_blocker ON blocked_users(blocker_id);
CREATE INDEX IF NOT EXISTS idx_blocked_users_blocked ON blocked_users(blocked_id);

-- Data export tracking
CREATE TABLE IF NOT EXISTS data_exports (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  file_url TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_data_exports_user ON data_exports(user_id, created_at DESC);


-- ============================================================================
-- schema-migration-admin-depth.sql
-- ============================================================================
-- Phase 4: Admin & Verification depth
-- verification_requests: badge applications + face/id moderation queue
CREATE TABLE IF NOT EXISTS verification_requests (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  requested_badge VARCHAR(50) DEFAULT '',
  cost_paid INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  admin_notes TEXT DEFAULT '',
  reviewed_by INTEGER REFERENCES users(id),
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_vr_type CHECK (type IN ('badge', 'face', 'id')),
  CONSTRAINT valid_vr_status CHECK (status IN ('pending', 'approved', 'rejected'))
);
CREATE INDEX IF NOT EXISTS idx_vr_user_type ON verification_requests(user_id, type);
CREATE INDEX IF NOT EXISTS idx_vr_status ON verification_requests(status);
CREATE INDEX IF NOT EXISTS idx_vr_created_at ON verification_requests(created_at DESC);

INSERT INTO feature_flags (key, enabled, description) VALUES
  ('badge_verification', true, 'Allow users to request verified badges'),
  ('face_verification', true, 'Allow users to submit face verification photos'),
  ('economy_controls', true, 'Allow admins to adjust user points/tokens')
ON CONFLICT DO NOTHING;


-- ---------------- Merge complete ----------------
-- Defined/ensured tables: users, follows, posts, media, likes, comments, comment_likes, post_unlocks, poll_options, poll_votes, link_previews, hashtags, post_hashtags, stories, story_views, story_reactions, rooms, room_messages, channels, channel_subscriptions, channel_members, conversations, messages, notifications, verifications, transactions, wallet_addresses, boosts, referrals, reports, admin_logs, feature_flags, app_config, post_views, message_reactions, message_pins, conversation_blocks, conversation_mutes, group_conversations, group_members, group_messages, group_message_reactions, channel_mutes, channel_verifications, group_verifications, room_speakers, room_hearts, calls, call_signals, point_ledger, ad_views, hypelab_events, token_claims, tips, shop_listings, shop_purchases, swaps, blocked_users, data_exports, verification_requests
